data:
  search:
    # split: False # split training data into train/val set
    # sp_ratio: 0.5 # split ratio
    train: './data/ILSVRC2012' # path to train data (ImageNet)
    val: '' # path to validation data (ImageNet)
    type: 'CIFAR10'
    jitter: False
    # type: 'MNIST'
    # type: 'ImageNet'
  augment:
    split: False
    train: ''
    val: ''
    type: 'CIFAR10'
    jitter: False
    # type: 'MNIST'
    # type: 'ImageNet'
---
train:
  split: True
  w_data_ratio: 0.9
  trn_batch_size: 64
  val_batch_size: 64
  workers: 4
  w_optim:
    type: 'sgd'
    lr: 0.035
    lr_min: 0.0
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    # type: 'adabound'
    # lr: 0.001
    # final_lr: 0.05
  a_optim:
    type: 'adam'
    lr: 0.006
    betas: 
      - 0.0
      - 0.999
    momentum: 0.9
    weight_decay: 0.001
  lr_schduler:
    type: 'cosine'
  w_grad_clip: 0.0
  drop_path_prob: 0.0
  warmup_epochs: 5
  epochs: 200
  print_freq: 200
  save_freq: 50
  plot_path: './searchs'
  gt_file: './searchs'
  architect:
    n_samples: 2
    renorm: True
---
valid:
  trn_batch_size: 64
  val_batch_size: 64
  workers: 4
  epochs: 600
  genotype: ''
  gt_file: ''
  w_optim:
    type: 'sgd'
    lr: 0.1
    lr_min: 0.0
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True
  aux_weight: 0.0
  drop_path_prob: 0.0
  w_grad_clip: 0.0
  print_freq: 200
  save_freq: 50
---
model:
  type: 'proxyless-nas'
  classes: 10             # use 10 for MNIST, CIFAR10
  channel_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
  channel_init: 16        # init channel
  channel_multiplier: 1   # init channel multiplier
  groups: 3               # num of nodes (states) per layer
  blocks: 18              # num of DAG layers (cells) in model
  alpha: 84
  conv_groups: 2
  bottleneck_ratio: 4
  path_drop_rate: 0.1
  dropout_rate: 0.0
  use_avg: False
  bn_before_add: True
  pxl_ops_order: 'bn_act_weight'
  ops_order: 'bn_act_weight'
  sepconv_stack: False
  affine: False
  samples: 1
  w_latency: 0
  label_smoothing: False
  verbose: False
---
genotypes:
  - 'dil_conv_3x3'
  - 'skip_connect' # identity
  - 'sep_conv_3x3'
  - 'sep_conv_5x5'
  - 'sep_conv_7x7'
  - 'avg_pool_3x3'
  - 'max_pool_3x3'
  # - 'dil_conv_5x5'
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
device:
  gpus: 'all'
  seed: 2
