data:
  search:
    # split: False # split training data into train/val set
    # sp_ratio: 0.5 # split ratio
    train: './data/ILSVRC2012' # path to train data (ImageNet)
    val: '' # path to validation data (ImageNet)
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
  augment:
    split: False
    train: ''
    val: ''
    type: 'CIFAR10'
    # type: 'MNIST'
    # type: 'ImageNet'
---
train:
  split: True
  w_data_ratio: 0.9
  trn_batch_size: 50
  val_batch_size: 50
  workers: 0
  w_optim:
    type: 'sgd'
    lr: 0.025
    lr_min: 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001
    # type: 'adabound'
    # lr: 0.001
    # final_lr: 0.05
  a_optim:
    type: 'adam'
    lr: 0.006
    momentum: 0.9
    weight_decay: 0.001
  lr_schduler:
    type: 'cosine'
  w_grad_clip: 5.
  warmup_epochs: 100
  epochs: 200
  print_freq: 50
  plot_path: './searchs'
---
valid:
  trn_batch_size: 50
  val_batch_size: 50
  workers: 0
  genotype: ''
  gt_file: ''
  epochs: 600
  aux_weight: 0.
---
model:
  type: 'proxyless-nas'
  classes: 10             # use 10 for MNIST, CIFAR10
  channel_in: 3           # 3 for ImageNet/CIFAR10, 1 for MNIST
  channel_init: 16        # init channel
  channel_multiplier: 1   # init channel multiplier
  groups: 1                # num of nodes (states) per layer
  blocks: 3              # num of DAG layers (cells) in model
  alpha: 48.0
  conv_groups: 2
  samples: 1
  w_latency: 0.0
---
genotypes:
  - 'max_pool_3x3'
  - 'avg_pool_3x3'
  - 'skip_connect' # identity
  - 'sep_conv_3x3'
  - 'sep_conv_5x5'
  - 'dil_conv_3x3'
  - 'dil_conv_5x5'
  # - 'sep_conv_7x7',
  - 'none'
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
device:
  gpus: 'all'
  seed: 2
